//
// auto-generated by mm.py
//
#include <iostream>
#include "full_matrix/Computation.hpp"
#include "Arguments.hpp"
#include "Data.hpp"
#include "IndexGenerator.hpp"

using namespace MM;
using namespace MM::full_matrix;

//user function
inline void anonymusAt5040(NeighProxy<CellData<2>> x,
				double& y) {
				    y = -x[{1,1}]  - x[{1,0}]   - x[{1,-1}]
					-x[{0,1}]  + 8*x[{0,0}] - x[{0,-1}]
					-x[{-1,1}] - x[{-1,0}]  -x[{-1,-1}];
			    }

// host stub function
void mm_par_loop_anonymusAt5040(std::string name, Computation<2> &computation,
 NEIGH<CellData<2>> arg0, OUT<CellData<2>> arg1) {
  const std::array<std::size_t, 2> &begin = computation.index_generator.get_begin();
  const std::array<std::size_t, 2> &end = computation.index_generator.get_end();
  for (std::size_t j = begin[1]; j < end[1]; j++) {
    for (std::size_t i = begin[0]; i < end[0]; i++) {
      const Coords<2> coords(i, j);
      std::size_t mat_index = 0;
      anonymusAt5040(arg0.get(coords, mat_index),
        arg1.get(coords, mat_index));
    }
  }
}
