//
// auto-generated by mm.py
//
#include <iostream>
#include "full_matrix/Computation.hpp"
#include "Arguments.hpp"
#include "Data.hpp"
#include "IndexGenerator.hpp"

using namespace MM;
using namespace MM::full_matrix;

//user function
inline void anonymusAt3037(double density,
			  double volume,
			  double& mass) {
		mass = density * volume;
	};

// host stub function
void mm_par_loop_anonymusAt3037(std::string name, Computation<2> &computation,
 IN<CellMatData<2>> arg0, IN<CellMatData<2>> arg1, OUT<CellMatData<2>> arg2) {
  const std::array<std::size_t, 2> &begin = computation.index_generator.get_begin();
  const std::array<std::size_t, 2> &end = computation.index_generator.get_end();
  for (std::size_t j = begin[1]; j < end[1]; j++) {
    for (std::size_t i = begin[0]; i < end[0]; i++) {
      const Coords<2> coords(i, j);
      for (std::size_t mat_index = 0; mat_index < computation.data.get_mat_number(); mat_index++) {
        anonymusAt3037(arg0.get(coords, mat_index),
          arg1.get(coords, mat_index),
          arg2.get(coords, mat_index));
      }
    }
  }
}
