//
// auto-generated by mm.py
//
#include <iostream>
#include "MultidimArray.hpp"
#include "compressed_cell_centric/Arguments.hpp"
#include "compressed_cell_centric/Computation.hpp"

using namespace MM;
using namespace MM::compressed_cell_centric;

#define NeighProxy NeighProxyDirect

//user function
inline void anonymusAt3201(double &p, double n, double rho, double t, double Vf) {
      if (Vf > 0) p = (n * rho * t) / Vf;
      else p = 0;
      }

// host stub function
void mm_par_loop_anonymusAt3201(std::string name, Computation<2> &computation,
 OUT<CellMatData<2>> arg0, IN<MatData<2>> arg1, IN<CellMatData<2>> arg2, IN<CellMatData<2>> arg3,
 IN<CellMatData<2>> arg4) {
  const std::array<std::size_t, 2> &begin = computation.index_generator.get_begin();
  const std::array<std::size_t, 2> &end = computation.index_generator.get_end();

  CompressedDataStructure &structure = computation.data.structure;
  std::array<std::size_t,2> shape = computation.data.get_size();
  double * __restrict data0 = arg0.get_raw();
  double *__restrict data0_list = arg0.get_raw_list();
  double * __restrict data1 = arg1.get_raw();
  double * __restrict data2 = arg2.get_raw();
  double *__restrict data2_list = arg2.get_raw_list();
  double * __restrict data3 = arg3.get_raw();
  double *__restrict data3_list = arg3.get_raw_list();
  double * __restrict data4 = arg4.get_raw();
  double *__restrict data4_list = arg4.get_raw_list();
  #pragma omp parallel for collapse(1)
  for (std::size_t j = begin[1]; j < end[1]; j++) {
    #pragma omp simd
    for (std::size_t i = begin[0]; i < end[0]; i++) {
      if (structure.structure[i+j*shape[0]].nmats == 1) {
        std::size_t mat_index = structure.structure[i+j*shape[0]].imat;
        anonymusAt3201(
          data0[i+j*shape[0]],
          data1[mat_index],
          data2[i+j*shape[0]],
          data3[i+j*shape[0]],
          data4[i+j*shape[0]]);
      } else {
        for (std::size_t structure_index = structure.structure[i+j*shape[0]].imat; 
            structure_index!=-1ul; structure_index = structure.mixed_storage[structure_index].nextfrac) {
          std::size_t mat_index = structure.mixed_storage[structure_index].material;
          anonymusAt3201(
            data0_list[structure_index],
            data1[mat_index],
            data2_list[structure_index],
            data3_list[structure_index],
            data4_list[structure_index]);
        }
      }
    }
  }
}
