//
// auto-generated by mm.py
//
#include <iostream>
#include "full_matrix/Computation.hpp"
#include "Arguments.hpp"
#include "Data.hpp"
#include "IndexGenerator.hpp"

using namespace MM;
using namespace MM::full_matrix;

#define NeighProxy NeighProxyDirect

//user function
inline void anonymusAt1258(double &p, double n, double rho, double t, double Vf) {
      if (Vf > 0) p = (n * rho * t) / Vf;
      else p = 0;
      }

// host stub function
void mm_par_loop_anonymusAt1258(std::string name, Computation<2> &computation,
 OUT<CellMatData<2>> arg0, IN<MatData<2>> arg1, IN<CellMatData<2>> arg2, IN<CellMatData<2>> arg3,
 IN<CellMatData<2>> arg4) {
  const std::array<std::size_t, 2> &begin = computation.index_generator.get_begin();
  const std::array<std::size_t, 2> &end = computation.index_generator.get_end();
  std::array<std::size_t,2> shape0;
  double * __restrict data0 = arg0.get_raw(shape0);
  std::array<std::size_t,2> shape1;
  double * __restrict data1 = arg1.get_raw(shape1);
  std::array<std::size_t,2> shape2;
  double * __restrict data2 = arg2.get_raw(shape2);
  std::array<std::size_t,2> shape3;
  double * __restrict data3 = arg3.get_raw(shape3);
  std::array<std::size_t,2> shape4;
  double * __restrict data4 = arg4.get_raw(shape4);
  for (std::size_t mat_index = 0; mat_index < computation.data.get_mat_number(); mat_index++) {
    #pragma omp parallel for collapse(1)
    for (std::size_t j = begin[1]; j < end[1]; j++) {
      #pragma omp simd
      for (std::size_t i = begin[0]; i < end[0]; i++) {
        const Coords<2> coords(i, j);
        anonymusAt1258(
          data0[i+j*shape0[0]+mat_index*shape0[0]*shape0[1]],
          data1[mat_index],
          data2[i+j*shape2[0]+mat_index*shape2[0]*shape2[1]],
          data3[i+j*shape3[0]+mat_index*shape3[0]*shape3[1]],
          data4[i+j*shape4[0]+mat_index*shape4[0]*shape4[1]]);
      }
    }
  }
}
